import {Dimensions, StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  row: {
    flexDirection: 'row',
    marginTop: 25,
  },
  card: {
    width: 150,
    height: 150,
    backgroundColor: '#ffffff',
    marginTop: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.9,
    shadowRadius: 2,
    elevation: 8,
    marginLeft: 30,
    alignItems: 'center',
  },
  header: {
    marginLeft: '3%',
    fontSize: 20,
    fontFamily: 'poppins',
    color: '#39D5D5',
    marginTop: 10,
    fontWeight: '700',
  },
  detail: {
    marginLeft: '3%',
    fontSize: 16,
    fontFamily: 'poppins',
    color: '#39D5D5',
    marginTop: 15,
    lineHeight: 25,
    textAlign: 'center',
  },
  icon: {
    fontSize: 60,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 15,
  },
  modal: {
    backgroundColor: '#ffffff',
    height: '35%',
    borderRadius: 5,
    width: '85%',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  modal_button_container: {
    marginTop: 40,
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  modal_button_cancel: {
    backgroundColor: '#FF2E2E',
    borderRadius: 5,
    marginLeft: 10,
    width: 100,
  },
  modal_button: {
    backgroundColor: '#39D5D5',
    borderRadius: 5,
    marginLeft: 20,
    width: 100,
  },
  button_text: {
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
    color: '#ffffff',
    padding: 10,
  },
  picker_text: {
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
  },
  modal_text: {
    marginTop: 20,
    fontSize: 22,
    color: '#39D5D5',
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
    marginBottom: 15,
  },
  picker_text: {
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
  },
});
