export const _navigation = {
  Home: 'Home',
  Profile: 'Profile',
  EditProfile: 'EditProfile',
  ChangePassword: 'ChangePassword',
  AllProducts: 'AllProducts',
  ProductDetail: 'ProductDetail',
  LogIn: 'LogIn',
  Register: 'Register',
  OrderManager: 'OrderManage',
  OrderDetail: 'OrderDetail',
  FamilyManager: 'FamilyManage',
  FamilyDetail: 'FamilyDetail',
  CulturalFamily: 'CulturalFamily',
  Military: 'Military',
};
