import {StyleSheet, Dimensions} from 'react-native';
var {width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    marginBottom: 10,
  },
  info_view: {
    flexDirection: 'row',
    marginTop: 12,
    marginLeft: 10,
  },
  info_view_list: {
    flexDirection: 'row',
    marginTop: 12,
    marginLeft: 10,
    borderBottomWidth: 0.2,
    marginRight: 10,
  },
  info_view_member: {
    flexDirection: 'row',
    marginTop: 10,
    marginLeft: 30,
  },
  title: {
    fontSize: 18,
    color: '#39D5D5',
    fontFamily: 'poppins',
    fontWeight: '700',
  },
  detail: {
    fontSize: 18,
    fontFamily: 'poppins',
    marginLeft: 5,
  },
  detail_red: {
    fontSize: 18,
    fontFamily: 'poppins',
    marginLeft: 5,
    color: '#FF2E2E',
  },
  detail_green: {
    fontSize: 18,
    fontFamily: 'poppins',
    marginLeft: 5,
    color: '#00A300',
  },
  productCard: {
    width: (width * 9) / 10,
    height: 100,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 20,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderColor: 'silver',
    paddingBottom: 10,
  },
  image: {
    resizeMode: 'cover',
    width: (width * 3) / 10,
    height: '100%',
    borderRadius: 5,
  },
  info_container: {
    flex: 1,
    backgroundColor: 'transparent',
    padding: 10,
    justifyContent: 'space-between',
  },
  name_container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  name: {
    fontWeight: 'bold',
    fontSize: 20,
  },
  miniButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  removeButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 30,
    height: 30,
    backgroundColor: 'white',
    borderRadius: 50,
    backgroundColor: '#39D5D5',
  },
  remove: {
    fontWeight: 'bold',
    fontSize: 14,
    color: 'black',
  },
  total_container: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  total_text: {
    paddingHorizontal: 8,
    fontWeight: 'bold',
    fontSize: 20,
  },
  total_price: {
    fontWeight: 'bold',
    color: '#33c37d',
    fontSize: 20,
  },
  price: {
    fontWeight: 'bold',
    color: 'black',
    fontSize: 20,
  },

  button_cultural: {
    backgroundColor: '#39D5D5',
    borderRadius: 5,
    width: '60%',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 30,
  },
  button_need: {
    backgroundColor: '#33c37d',
    borderRadius: 5,
    width: '60%',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 30,
  },
  button_text: {
    fontSize: 20,
    color: '#ffffff',
    fontFamily: 'poppins',
    fontWeight: '700',
    padding: 15,
    textAlign: 'center',
  },
  modal: {
    backgroundColor: '#ffffff',
    height: '35%',
    borderRadius: 5,
  },
  modal_text: {
    marginTop: 20,
    fontSize: 22,
    color: '#39D5D5',
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
  },
  modal_button_container: {
    marginTop: 30,
    flexDirection: 'row',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  modal_button_cancel: {
    backgroundColor: '#FF2E2E',
    borderRadius: 5,
    marginLeft: 20,
  },
  modal_button: {
    backgroundColor: '#39D5D5',
    borderRadius: 5,
    marginLeft: 20,
  },
  button_text: {
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
    color: '#ffffff',
    padding: 10,
  },
  card_container: {
    width: 300,
    height: 270,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.9,
    shadowRadius: 2,
    elevation: 8,
    flex: 1,
    marginLeft: 20,
    marginBottom: 20,
    marginTop: 10,
  },
  card_container_cultural: {
    width: 300,
    height: 150,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.9,
    shadowRadius: 2,
    elevation: 8,
    flex: 1,
    marginLeft: 20,
    marginBottom: 20,
    marginTop: 10,
  },
  icon: {
    fontSize: 18,
    marginLeft: 10,
    marginTop: 5,
  },
});
