import {StyleSheet, Dimensions} from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  head: {height: 50, backgroundColor: '#39D5D5'},
  text_header: {
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'poppins',
    color: '#ffffff',
    fontWeight: '700',
  },
  row: {
    width: '95%',
    height: 55,
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 5,
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 5,
    alignItems: 'center',
  },
  text: {
    padding: 5,
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
  },
  pagination: {
    position: 'absolute',
    top: 680,
    flexDirection: 'row',
  },
  paginationButton: {
    backgroundColor: '#39D5D5',
    borderRadius: 5,
    padding: 5,
  },
  arrow: {
    fontSize: 30,
    color: '#ffffff',
  },
  page: {
    fontSize: 30,
    color: '#39D5D5',
    textAlign: 'center',
    fontFamily: 'poppins',
    fontWeight: '700',
    marginLeft: 30,
    marginRight: 30,
  },
  total: {
    fontSize: 18,
    textAlign: 'center',
    color: '#39D5D5',
    fontFamily: 'poppins',
    fontWeight: '700',
    marginLeft: 20,
    marginRight: 50,
    marginTop: 5,
  },
});
